### ISSUE TITLE
Nth Children

### ISSUE THREAD

**Issue by sackxay** [sackxay/image-grid#1]
Hey Thomas,
   For the first screen size I hid 2 photos with the nth-child command. I wrote 2 lines of css for each picture hidden. Is there a way to target 2 child elements with 1 nth-child command?

https://github.com/sackxay/image-grid/blob/gh-pages/css/main.css#L41
https://github.com/sackxay/image-grid/blob/gh-pages/css/main.css#L45

@thomasjbradley

**Comment by thomasjbradley** [comment]
Not any way to do it super easily, except something like using a comma:

```css
.photo:nth-child(2),
.photo:nth-child(5) {
  display: none;
}
```
